config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users

  resources :questions do
    resources :answers, only: [:create, :update, :edit, :new, :destroy]
    member do
      put "like", to: "questions#upvote"
      put "dislike", to: "questions#downvote"
    end
  end

  put  "answers/:id/like" => "answers#upvote", :as => :like_answer
  put  "answers/:id/dislike" => "answers#downvote", :as => :dislike_answer

  put  "questions/:id/set_answer" => "questions#set_answer", :as => :set_answer

  resources :comments, only: [:create, :update, :edit, :new, :destroy]

end

app/models/question.rb
class Question < ActiveRecord::Base
  acts_as_votable
  belongs_to :user, class_name: "User"
  has_many :comments, as: :commentable
  has_many :votes, as: :votable
  has_many :answers

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }
  validates_presence_of :user_id

  def rating
    self.get_upvotes.count - self.get_downvotes.count
  end

  def top_answer
    Answer.find_by_id self.selected_answer
  end

  def other_answers
    self.answers.where.not(id: self.top_answer)
  end

end

app/controllers/question_controller.rb
class QuestionController < ApplicationController
  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def require_login
    return true #unless is_authenticated?(params[:user_id])
    # redirect_to login w/ flash message or something like this
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]
  before_action :get_params, only: [:create, :update]

  def index
    @questions = Question.all.order(created_at: :desc)
  end

  def new
    @question = Question.new
  end

  def create
    new_question = Question.new(get_params)
    new_question.user = current_user
    if new_question.save
      flash[:success] = "Your question was saved"
      redirect_to root_path
    else
      flash[:error] = "Your question could not be saved"
      redirect_to new_question_path
    end
  end

  def show
    @question = Question.find_by(id: params[:id])
    @answer = Answer.new
  end

  def edit
    @question = Question.find_by(id: params[:id])
  end

  def update
    edited_question = Question.find_by(id: params[:id])
    if edited_question.update_attributes(get_params)
      flash[:success] = "Your question was updated"
      redirect_to edited_question
    else
      flash[:error] = "Your question could not be updated"
      redirect_to edited_question
    end
  end

  def destroy
    question = Question.find_by(id: params[:question_id])
    if current_user.id == question.user_id
      question.destroy
      flash[:success] = "Your question was deleted"
      redirect_to root_path
    else
      flash[:error] = "You are not authorized to delete this question."
      redirect_to root_path
    end
  end

  def upvote
    if logged_in?
      @question = Question.find_by id: params[:id]
      @question.upvote_by current_user
      redirect_to question_path
    else
      flash[:error] = "You must be logged in to do that"
        redirect_to :back
    end
  end

  def downvote
    if logged_in?
      @question = Question.find_by id: params[:id]
      @question.downvote_by current_user
      redirect_to question_path
    else
      flash[:error] = "You must be logged in to do that"
        redirect_to :back
    end
  end

  def set_answer
    question = Question.find_by_id params[:id]
    if current_user && current_user.id == question.user_id
      question.selected_answer = params[:answer_id]
      question.save
      redirect_to :back
    else
      flash[:error] = "You are not authorized to select a best answer for this question."
      redirect_to :back
    end
  end

  private

  def require_login
    return true unless !logged_in?
    else flash[:error] = "You must be logged in to do that."
    redirect_to :back
  end

  def get_params
    params.require(:question).permit :title, :body, :selected_answer
  end

end

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title, class: "form-control", value: @question.title %>
  <br />
  <%= f.label :body %>:
  <%= f.text_area :body, class: "form-control", :size => "25x20", placeholder: "Please give a detailed description of your problem"  %>
  <br />

  <%= f.submit class: "btn btn-default"%>
<% end %>

app/views/questions/_new_modal.html.erb
<div class="modal fade" id="questionModal" tabindex="-1" role="dialog" aria-labelledby="questionLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="answerLabel">What is your question?</h4>
      </div>
      <div class="modal-body">
        <%= form_for Question.new do |f| %>
          <%= f.label :title %> of Question:
          <%= f.text_field :title, class: "form-control", placeholder: "Title of Question Here" %>
          <br>
          <%= f.label :body %> of Question:
          <%= f.text_area :body, class: "form-control", :size => "25x20", placeholder: "Please describe your question in detail."  %>
          <%= f.submit class: "btn btn-default modal-button"%>
        <% end %>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

app/views/questions/_question.html.erb
<div>
<div class='question-stats'>
  <span class="score"><%= question.rating%></span>
  <br>
  <div class='votes'>score</div>
</div>
<div class='question-stats'>
  <span class="num-answers"><%= question.answers.count %></span>
  <br>
  <div class='votes'>answers</div>
</div>
<%=link_to question.title, question_path(question), :class=> "question-title" %>
<br>
<span>Posted by <%= link_to question.user.username, question.user %> <%= distance_of_time_in_words(question.created_at, Time.now) %> ago</span>
</div>
<br>

app/views/questions/edit.html.erb
<%= render "form" %>
<br>
<%= link_to "Cancel", question_path(@question), class: "btn btn-default"%>

app/views/questions/index.html.erb
<h3 id="index-heading">Questions</h3>
<% unless @questions.empty? %>
  <%= render @questions %>
<% else %>
  <h5>There are no questions</h5>
<% end %>

app/views/questions/new.html.erb
<%= render "form" %>
<%= link_to "Cancel", root_path%>

app/views/questions/show.html.erb
<!-- could be a render with the questions and answers and comments on it -->
<h3>Question</h3>
<div class='question'>
  <span class='question-title'><%=@question.title%></span>
  <% if logged_in? && current_user.id == @question.user_id%>
    <%= link_to content_tag(:i, "", class: ['fa', 'fa-pencil-square-o']), edit_question_path%> |
    <%= link_to content_tag(:i, "", class: ['fa', 'fa-times']), question_path(question_id: @question.id), method: :delete %>
  <%end%>
  <div>Asked by <%=link_to @question.user.username, @question.user %> <%= distance_of_time_in_words(@question.created_at, Time.now) %> ago</em></div>
  <div class='div-votes'>
    <%= link_to '<i class="fa fa-2x fa-caret-up"></i>'.html_safe, like_question_path(@question), method: :put %>
    <br>
    <span class='vote-count'><%= @question.rating%></span>
    <br>
    <%= link_to '<i class="fa fa-2x fa-caret-down"></i>'.html_safe, dislike_question_path(@question), method: :put %>
  </div>
  <p class='question-body'><%=@question.body%></p>
  <br>
  <a style="cursor: pointer;" class='show-comment'>comment</a>
  <div class="comment-form"><%= render partial: 'comments/form', locals: {id_type: "question", id: @question.id} %></div>
  <%= render partial: @question.comments.where(commentable_type: "Question").order(created_at: :desc) %>
  <% if current_user && current_user != @question.user %>
  <hr>
    <button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#answerModal">
      Answer This Question
    </button>

    <div class="modal fade" id="answerModal" tabindex="-1" role="dialog" aria-labelledby="answerLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="answerLabel">Create Your Answer</h4>
          </div>
          <div class="modal-body">
            <%= render 'answers/form' %>
            <div class="modal-footer">
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% if @question.answers.length > 0 %>
  <% if @question.top_answer %>
    <div id='top-answer'>
      <h3>Top Answer</h3>
      <%= render @question.top_answer %>
    </div>
  <% end %>
  <% if @question.other_answers.length > 0 %>
    <h3>Other Answers</h3>
    <%= render @question.other_answers %>
  <% end %>
<% else %>
  <h3>no answers yet</h3>
<%end %>