config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users

  resources :questions do
    resources :answers, only: [:create, :update, :edit, :new, :destroy]
    member do
      put "like", to: "questions#upvote"
      put "dislike", to: "questions#downvote"
    end
  end

  put  "answers/:id/like" => "answers#upvote", :as => :like_answer
  put  "answers/:id/dislike" => "answers#downvote", :as => :dislike_answer

  put  "questions/:id/set_answer" => "questions#set_answer", :as => :set_answer

  resources :comments, only: [:create, :update, :edit, :new, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  has_many :comments, as: :commentable
  belongs_to :commentable
  belongs_to :author, class_name: "User"


  validates :body, presence: true, length: { minimum: 2, maximum: 160 }
  validates_presence_of :author_id

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, only: [:new, :create]

  def create
    if params[:question]
      question = Question.find_by id: params[:question]
      new_comment = question.comments.build(body: params[:body], author_id: current_user.id)
    elsif params[:answer]
      answer = Answer.find_by id: params[:answer]
      new_comment = answer.comments.build(body: params[:body], author_id: current_user.id)
    else
      comment = Comment.find_by id: params[:comment]
      new_comment = comment.comments.build(body: params[:body], author_id: current_user.id)
    end

    if new_comment.save
      flash[:success] = "Your comment was saved"
      redirect_to :back
    else
      flash[:error] = "Unable to delete comment."
      redirect_to :back
    end
  end

  def destroy
    comment = Comment.find_by id: params[:comment_id]
    if current_user.id == comment.author_id
      comment.destroy
        flash[:success] = "Your comment was deleted"
        redirect_to :back
    else
      flash[:error] = "You are not authorized to delete this comment."
      redirect_to :back
    end
  end

  private

  def require_login
    return true unless !logged_in?
    else flash[:error] = "You must be logged in to do that."
    redirect_to :back
  end

end

app/views/comments/_comment.html.erb
<% nested = 'nested' if comment.commentable_type == "Comment" %>
<div class="comment <%= nested %>">
  <hr>
  <br>
  <span class='comment-heading'><%= distance_of_time_in_words(comment.created_at, Time.now) %> ago, <%=link_to comment.author.username, comment.author %> commented</span>
  <br>
  <%=comment.body%>
  <% if current_user == comment.author %>
    <%= link_to content_tag(:i, "", class: ['fa', 'fa-times']), comment_path(comment_id: comment.id), method: :delete %><br>
  <% end %>
  <% unless nested %>
    <a style="cursor: pointer;" class='show-comment'>comment</a>
  <% end %>
  <div class='comment-form'><%= render partial: 'comments/form', locals: {id_type: "comment", id: comment.id} %></div>
  <br>
<%= render partial: comment.comments %>
</div>

app/views/comments/_form.html.erb
<%= form_tag comments_path, method: :post do %>
  <% if @question %>
    <%= hidden_field_tag id_type, id %>
  <% end %>
  <%= text_field_tag :body %>
  <%= submit_tag "comment", class: "btn btn-default btn-sm" %>
<% end %>