config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users

  resources :questions do
    resources :answers, only: [:create, :update, :edit, :new, :destroy]
    member do
      put "like", to: "questions#upvote"
      put "dislike", to: "questions#downvote"
    end
  end

  put  "answers/:id/like" => "answers#upvote", :as => :like_answer
  put  "answers/:id/dislike" => "answers#downvote", :as => :dislike_answer

  put  "questions/:id/set_answer" => "questions#set_answer", :as => :set_answer

  resources :comments, only: [:create, :update, :edit, :new, :destroy]

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  acts_as_votable
	belongs_to :question
	belongs_to :author, class_name: 'User'
	has_many :comments, as: :commentable
	has_many :votes, as: :votable


	validates :body, presence: true, length: { minimum: 2 }
	validates_presence_of :author_id, :score, :question_id

  def rating
    self.get_upvotes.count - self.get_downvotes.count
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def create
		@answer = Answer.new(answer_params)
		@answer.author_id = session[:user_id]
		if @answer.save
			redirect_to question_path(@answer.question)
		else
			flash[:error] = "Your answer was not saved."
			redirect_to :back
		end
	end

	def destroy
		answer = Answer.find_by id: params[:id]
		if current_user.id == answer.author_id
			answer.destroy
			flash[:success] = "Your answer was deleted."
			redirect_to :back
		 else
      flash[:error] = "You are not authorized to delete this question."
      redirect_to :back
    end
	end

	def upvote
	  @answer = Answer.find_by id: params[:id]
	  @answer.upvote_by current_user
	  redirect_to :back
	end

	def downvote
	  @answer = Answer.find_by id: params[:id]
	  @answer.downvote_by current_user
	  redirect_to :back
	end

	private

	def answer_params
		params[:answer][:question_id] = params[:question_id]
		params.require(:answer).permit :body, :question_id
	end
end

app/views/answers/_answer.html.erb
<div class='answer'>
  <span class='comment-heading'><%= distance_of_time_in_words(answer.created_at, Time.now) %> ago, <%=link_to answer.author.username, answer.author %> answered</span>

  <% if logged_in? && current_user.id == answer.author_id%>
    <%= link_to content_tag(:i, "", class: ['fa', 'fa-times']), question_answer_path(question_id: @question.id, id: answer.id), method: :delete %>
  <%end%>

  <% if logged_in? && current_user.id == answer.question.user_id && answer.question.selected_answer != answer.id %>
    <%= link_to content_tag(:i, " Mark as Best Answer", class: ['fa', 'fa-check']), set_answer_path(:answer_id => answer.id ), method: :put %>
  <%end%>

  <br>

  <div class='div-votes'>
    <%= link_to '<i class="fa fa-2x fa-caret-up"></i>'.html_safe, like_answer_path(answer), method: :put %>
    <br>
    <span class='vote-count'><%= answer.rating%></span>
    <br>
    <%= link_to '<i class="fa fa-2x fa-caret-down"></i>'.html_safe, dislike_answer_path(answer), method: :put %>
  </div>

  <p class='answer-body'><%=answer.body%></p>

  <br>

  <a style="cursor: pointer;" class='show-comment'>comment</a>

  <div class='comment-form'>
    <%= render partial: 'comments/form', locals: {id_type: "answer", id: answer.id} %>
  </div>

  <%= render answer.comments %>
  <br>
</div>

app/views/answers/_form.html.erb
<%= form_for @answer, url: "/questions/#{params[:id]}/answers" do |f| %>
	<%= f.text_area :body, class: "form-control", :size => "25x20"  %>
	 <%= f.submit class: "btn btn-default modal-button"%>
<% end %>

app/views/answers/edit.html.erb
<%= render 'form' %>